# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: lasertank3-serverless

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-3
#  deploymentBucket: lasertank3-serverless
#  memorySize: 1024
#  timeout: 5
#  versionFunctions: false
#  role: serverlessRole

#resources:
#  Resources:
#    serverlessRole:
#      Type: AWS::IAM::Role
#      Properties:
#        Path: /
#        RoleName: ServerlessRole
#        AssumeRolePolicyDocument:
#          Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Principal:
#                Service:
#                  - lambda.amazonaws.com
#              Action: sts:AssumeRole
#        ManagedPolicyArns:
#          - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
#          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
#        Policies:
#          - PolicyName: myPolicyName
#            PolicyDocument:
#              Version: '2012-10-17'
#              Statement:
#                - Effect: Allow
#                  Action:
#                    - logs:CreateLogGroup
#                    - logs:CreateLogStream
#                    - logs:PutLogEvents
#                  Resource:
#                    - 'Fn::Join':
#                      - ':'
#                      -
#                        - 'arn:aws:logs'
#                        - Ref: 'AWS::Region'
#                        - Ref: 'AWS::AccountId'
#                        - 'log-group:/aws/lambda/*:*:*'


# The `functions` block defines what code to deploy
functions:
  load:
    handler: index.load
    timeout: 2
    events:
      - http:
          path: load
          method: post
          cors: true

  list:
    handler: index.list
    timeout: 2
    events:
      - http:
          path: list
          method: get
          cors: true
